encoder_class: PlaceholderEncoder
encoder_parameters: {}
model_class: TransformerBinarySelectionModelWiggleAct
model_hyperparameters:
  d_model_per_head: 32
  dim_feedforward: 1024
  dropout_prob: 0.1
  known_token_count: 22
  layer_count: 5
  model_type: dasm
  multihit_model_name: ThriftyHumV0.2-59-hc-tangshm
  neutral_model_name: ThriftyHumV0.2-59
  nhead: 8
  output_dim: 20
  train_timestamp: 2025-06-23T17:29
serialization_version: 0
training_hyperparameters:
  batch_size: 1024
  learning_rate: 0.001
  min_learning_rate: 1.0e-06
  optimizer_name: RMSprop
  weight_decay: 1.0e-06
